version: "3"

services:
  php70-fpm:
    build:
      context: ./7.0/fpm
      args:
          - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www:cached

  php71-fpm:
    build:
      context: ./7.1/fpm
      args:
          - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www:cached

  php72-fpm:
    build:
      context: ./7.2/fpm
      args:
          - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www:cached

  php70-cli:
    build:
      context: ./7.0/cli
      args:
          - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www:cached

  php71-cli:
    build:
      context: ./7.1/cli
      args:
          - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www:cached

  php72-cli:
    build:
      context: ./7.2/cli
      args:
          - XDEBUG_ENABLED=1
    volumes:
      - ./:/var/www:cached